# Generated by Django 4.1 on 2023-01-18 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tablero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pub', models.DateTimeField(verbose_name='date published')),
                ('nivel', models.IntegerField(default=1)),
                ('sudoku_inicial', models.CharField(max_length=81)),
                ('sudoku_final', models.CharField(max_length=81)),
            ],
        ),
    ]
