# Generated by Django 4.1 on 2023-01-20 22:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdoku', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablero',
            name='fecha_pub',
        ),
        migrations.RemoveField(
            model_name='tablero',
            name='nivel',
        ),
        migrations.RemoveField(
            model_name='tablero',
            name='sudoku_final',
        ),
        migrations.RemoveField(
            model_name='tablero',
            name='sudoku_inicial',
        ),
        migrations.AddField(
            model_name='tablero',
            name='final_sudoku',
            field=models.CharField(default='0', max_length=81),
        ),
        migrations.AddField(
            model_name='tablero',
            name='initial_sudoku',
            field=models.CharField(default='0', max_length=81),
        ),
        migrations.AddField(
            model_name='tablero',
            name='level',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='tablero',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='tablero',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 20, 19, 27, 52, 376358, tzinfo=datetime.timezone.utc)),
        ),
    ]
