# Generated by Django 4.1 on 2023-01-21 03:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appdoku', '0002_remove_tablero_fecha_pub_remove_tablero_nivel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablero',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='tablero',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tablero',
            name='size',
            field=models.CharField(choices=[('2', '2x2'), ('3', '3x3')], default='3', max_length=30),
        ),
        migrations.AlterField(
            model_name='tablero',
            name='level',
            field=models.CharField(choices=[('1', 'baja'), ('2', 'media'), ('3', 'alta')], default='2', max_length=30),
        ),
        migrations.AlterField(
            model_name='tablero',
            name='name',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
