# Generated by Django 4.1 on 2023-01-21 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdoku', '0003_remove_tablero_pub_date_tablero_created_tablero_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablero',
            name='level',
            field=models.CharField(choices=[('1', 'bajo'), ('2', 'medio'), ('3', 'alto')], default='1', max_length=30),
        ),
        migrations.AlterField(
            model_name='tablero',
            name='size',
            field=models.CharField(choices=[('2', '2x2'), ('3', '3x3')], default='2', max_length=30),
        ),
    ]
