# Generated by Django 4.1 on 2023-01-22 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdoku', '0004_alter_tablero_level_alter_tablero_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablero',
            name='level',
            field=models.CharField(choices=[('1', 'bajo'), ('2', 'medio'), ('3', 'alto')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='tablero',
            name='size',
            field=models.CharField(choices=[('2', '2x2'), ('3', '3x3')], default='2', max_length=1),
        ),
    ]
